[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description="e"
[tool.poetry.dependencies]
python = "^3.8"
motor = "^2.1.0"
dnspython = "^1.16.0"
aiohttp = "^3.6.2"
